language: node_js
addons:
  apt:
    packages:
    - sshpass
node_js:
- 8.9.3
after_success:
- export SSHPASS=$DEPLOY_SERVER_PASSWORD
- sshpass -e ssh jack@$DEPLOY_SERVER_IP -o stricthostkeychecking=no 'cd /home/jack/xd_tech_community && git pull && npm i && npm run build'
env:
  global:
  - secure: epWAAY4T9OoCBGcb2/4jbMNU5dg+avZiT6Fxu1G7Ds+aoc8TUQnmgt70rA10CHOslM3S9rxCYWEQjkI74G7dWsAujO9CyDdzsDMdF7PEpbkC+Pj+wu8x6sFOhnKnNydoR4QAEA4IaU6ECIMtKJmXHSEcsk/cI1AqkMXJRhFJtOhPxXKl4s6+CFhzkMBnWffsZgSkmnNNguXl8ae5DcSZXIttWbR8c+MKiyJFaf9XlTBf9iDRFnTNdMOybkNTTzn1UMeKG1ENMyBUdZVT+RVxHkeIoNmpqDAms13siKlP7goAVl9Sr33LAOyrYpuUr/ixd+UdJyMEJk+IKEp0MyzWLQbwoKZJ3wPWxD42ST25TU18F0j6AQhrWWBUfVE3PWOHhX+NGi0s7+zPJf50QWuLcQOpquh97NCk8833ji8j8KYiHhWh0WaaYpKwrpWytMpsnDWBKl0MSD7ZC72HUjPvDRYg6vcnuV54pvrIZIaFEiS9h4EZ8WEq+ZJoR3HjtJyOclALF9hQVpmauOR16YA70a6/30d+W2d/QGBd6NkKG72dYAlS0KZl1hLhxB1663GnwW5tJF3UCIgYrhgKm6Um1Lh3xLv1q+wtwERFSSvnE1auEyWlCCyfK7hsCKz4RPEfQAfaQBbO12jc1HtDRXRIy4Gxr5mFYTpn80BcYscIH4k=
  - secure: sqbS+PBSI03gGoi7H/69XxCi2f7AOLbR7swbrqLwyzdh7StGqZLD1QjxxP95sck3TqvyqAqavL5+btD4s8YH1L7Gi0QSNwyilk9m6QyaSiMYqhfBgGT7QdP16rMiAvvTtK2X47fuMTg/GVtab8cV+/X0mPlCnf+UPGcOvoVye5mpT1eZviFrL1aHTrrNWPUOraNUl7JtnxCcH4RFcUxmWUWA7dRZzF2ZU7XDGO/ST5U8GesKfT3lwd3QS20t0Bpk1iW9JqAFCbw195+vEEVsFGDpeQlba1CXGtdHG7wZDTbCQkuMo0RsN6wB+Y6I+H7CPOoA53XApiey8JIRm88h3yUUgWP/BB+ecwRvE24tn1ouEg/nzqVvNOPtGSWzjsKqnU7n65v4nJK5fOMhv8DczKmLq7zLJHv6U4r9oDFGGutmq8uEyB7+c4zQ4gEU5/2/RYZnGLKIUzRX9ui5Ny+vSisWZqXkV0wPQKZnRTpRHhDok7y58UyAM7YZK1QcvG6V777HZXu75p40xc7gawZAsfz9iej0eosg+bYAzwDaWT9HyPSR8xj/xHmlgtouRLCXPEetPwpB3Bub9XQER1bTzeKwQpKInzRlMtR2ZunkakPhHzJCz/xHX7rCxAAOvAxJFv6XDYueKYezHqGfXjsU5Hj/jiQyUBMnslSX3d8b7Yc=
